### ISSUE TITLE
Migrarate to typst.ts

### ISSUE THREAD

**Issue by kwinso** [fenjalien/obsidian-typst#28]
What about [typst.ts](https://github.com/Myriad-Dreamin/typst.ts)? I think it will remove a lot of complexity. Also, the bundle size is smaller than the current implementation.

It can compile in memory file, as shown [here](https://github.com/Myriad-Dreamin/typst.ts/issues/345).

It will eliminate a lot of troubles like mobile file reading, as we'll stay in JS async land, so there's no need on round trips between rust and js. 

I think this will help with focusing on the actual functionality rather than fighting with bugs.

**Comment by fenjalien** [comment]
I've had many suggestions to use `typst.ts` and in short: no, I do not want to use it. 
- Completely lacking in documentation (I understand this is being worked on)
- It won't remove any complexity it'll just out source them instead, which would cause further problems
- No we won't stay in JS async land, `typst.ts` uses an access model concept which is essentially a bunch of callbacks. These are all required to be synchronous. The only reason it works is because of a synchronous xhr.
