### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by yonatankremer** [fenjalien/obsidian-typst#44]
it seems to be rendering using some bright grey color, barely visible on bright backgrounds

**Comment by fenjalien** [comment]
Thanks for the issue, but I can't do much without more information:
- What settings do you have?
- What other plugins do you have?
- Does it occur in a new vault, with only the plugin installed? If not, you could start copying settings and see when your issue occurs.
- What platform are you on? (obsidian version and Android/IOS/Windows/etc...
- Could you give screenshots of your issue?

**Comment by yonatankremer** [comment]
seems to be bright and low-res in the readme too. There's another person doing exactly this, both plugins aren't perfect ofc. You might be wanting to collaborate :)

**Comment by fenjalien** [comment]
I don't know what you are talking about, please be more clear and provide more information about your original issue.

**Comment by yonatankremer** [comment]
okay.

- let me know if any specific setting might be problematic, as there are lots of them, but I can't recall anything special.
- <img width="211" alt="Screenshot 2024-03-18 at 7 14 48 PM" src="https://github.com/fenjalien/obsidian-typst/assets/133390605/53a025d8-8696-4c35-8a65-d4a5f3ad911e">
- it is like that in a new vault. the rendering is still white, quite low res.
- macos

**Comment by fenjalien** [comment]
The settings you have for this plugin would be a good start.

I'm going to guess though you've got the render output option set to "image", you could try chaging it to SVG so it scales better. If you want to change any themeing have a look at the Preambles: https://github.com/fenjalien/obsidian-typst?tab=readme-ov-file#preambles

Another guess would be, because you are using MacOS your device has a [Retina Display](https://en.wikipedia.org/wiki/Retina_display) which has a higher pixel density. The images are not currently scaled by the pixel density but switching to the SVG render output may improve the outcome.

**Comment by yonatankremer** [comment]
have done all of it, doesn't seem to help.
