### ISSUE TITLE
[Bug] Not support Chinese words

### ISSUE THREAD

**Issue by xjxl520303** [fenjalien/obsidian-typst#55]
Can't correctly show Chinese characters in code block typst。

![image](https://github.com/fenjalien/obsidian-typst/assets/53321551/117a27ef-475f-487d-aadd-d9de1066f248)

**Comment by fenjalien** [comment]
It turns out Typst's default fonts do not contain any chinese glyphs. The Typst CLI and Webapp can automatically find and fallback to a font that supports the glyphs. For the plugin you need to tell it to load the correct fonts in the plugin settings, if you're using windows the font "Microsoft YaHei" works for me.

Unfortunately this is not supported on mobile, I should probably include a basic fallback for that case.

**Comment by xjxl520303** [comment]
> It turns out Typst's default fonts do not contain any chinese glyphs. The Typst CLI and Webapp can automatically find and fallback to a font that supports the glyphs. For the plugin you need to tell it to load the correct fonts in the plugin settings, if you're using windows the font "Microsoft YaHei" works for me.
> 
> Unfortunately this is not supported on mobile, I should probably include a basic fallback for that case.

Great! Tky, It works

![image](https://github.com/fenjalien/obsidian-typst/assets/53321551/13375087-1b2f-405f-ba14-a2b5cd637cd2)

**Comment by VincentTam** [comment]
Thanks.  This helps me a lot.
